### ISSUE TITLE
Styling issue?

### ISSUE THREAD

**Issue by xfq** [w3c/bp-i18n-specdev#131]
https://github.com/w3c/bp-i18n-specdev/blob/ab5f4d072a3e76727df094d8c10f9cc6654674fb/local.css#L259-L266

The code above doesn't seem to do what it intended to do? There should probably be descendant combinators before `td` and `code`, like:

```css
table.truncExample th,
table.truncExample td {
    vertical-align: top;
    }
    
table.truncExample kbd,
table.truncExample code {
    color: blue;
    font-size: larger;
    }
```
